# $$ MDSC - 201(p)$$

## $$ Assignment- 7$$

## $$ Tibble - & - Tidyverse$$

**Author : Akula Venkata Satya Sai Gopinadh**

**Date: 05-04-2023**

```{r}
library(tidyverse)
```

```{r}

as_tibble(iris)
```

### Creating a Tibble

```{r}
T <- tibble(
    x = 1.5,
    y=1,
    z=x+y
)
```

```{r}
print(T)
```

```{r}
a <- 1:10
```

```{r}
a
```

```{r}

tibble(a,a*2) 
```

### 3 columns: column b is dependent on a , column c is constant=1

```{r}
tibble(a,b=a*2,c=1)
```

```{r}
print(as_tibble(mtcars))
```

```{r}
print(as_tibble(mtcars),n=3)

```

```{r}
data <- data.frame(a = 1:3, b = letters[1:3], c = Sys.Date() - 1:3)

as_tibble(data)
```

```{r}
#Creating new tibble from column vectors
tibble(x= 1:5, y=1, z= x^3-y)
```

```{r}
#Creating new tibble from column vectors

tibble(x= 1:5, y=1, z= x^2+y)
```

```{r}

```

```{r}

```

```{r}
#tibble with a list
list_tibble <- tibble(x = 1:3,y = list(1:5, 1:10, 1:20))
list_tibble
```

```{r}

#creating a tibble with random values
tibble(x = runif(10),y=x*2)
```

#### Tibble with a list

```{r}
ltibble <- tibble(x = 1:3,y = list(1:5, 1:10, 1:20))
ltibble
```

### Subsetting

```{r}
df <- tibble(
    x = runif(5),
    y = rnorm(5)
)

df$x
```

```{r}

df[['x']]
```

```{r}

df[[2]]
```

```{r}
#creating columns in a tibble with names that start with a dot

tibble(.dotted :=3)
```

```{r}
#Unquoting an expression
x<-4
tibble(x=6,y=x)

```

```{r}
tibble(x=6,y = !!x)
```
